# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
require 'cucumber/rails'
require_relative './page_objects/base_page'
require 'capybara/apparition'
require 'capybara/cucumber'
require 'base64'
require 'webmock'
require 'selenium/webdriver'
include WebMock::API
include ActiveSupport::Testing::TimeHelpers

Dir[File.dirname(__FILE__) + '/page_objects/**/*.rb'].each { |f| require f }

ActionController::Base.allow_rescue = false

ENV['HOSTNAME'] = 'localhost'

After do |scenario|
  travel_back
  Capybara.reset_sessions!
end

