# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
require 'cucumber/rails'
require_relative './page_objects/base_page'
require 'capybara/apparition'
require 'capybara/cucumber'
require 'base64'
require 'webmock'
require 'selenium/webdriver'
include WebMock::API
include ActiveSupport::Testing::TimeHelpers

Dir[File.dirname(__FILE__) + '/page_objects/**/*.rb'].each { |f| require f }

ActionController::Base.allow_rescue = false

ENV['HOSTNAME'] = 'localhost'

After do |scenario|
  if scenario.failed? && Capybara.page.driver.respond_to?(:save_screenshot)
    begin
      report_dir = File.expand_path('../../cucumber-report', __FILE__)
      FileUtils.mkdir_p(report_dir)
      screenshot_path = File.join(report_dir, "screenshot_#{Time.now.to_i}.png")
      Capybara.page.save_screenshot(screenshot_path, full: true)
      # attach takes raw binary - the message formatter handles base64 encoding internally
      attach(File.binread(screenshot_path), 'image/png')
    rescue StandardError => e
      $stderr.puts "Screenshot capture failed: #{e.message}"
    end
  end
  travel_back
  Capybara.reset_sessions!
end

