# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - develop
      
pr:
  autoCancel: true
  branches:
    include:
      - develop
      - feature/*

variables:
  application.name: 'hwf-public'
  azure.subscription.endpoint: 'hmcts-pet'
  manual.branch.prefix: 'develop'


jobs:

  - job: TestApplication

    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
      rubyVersion: '= 2.5.5'
      bundlerVersion: '1.17.3'

    steps:
    - template: ./pipeline-steps/test-application.yaml
    - template: ./pipeline-steps/publish-tests.yaml


  - job: BuildAndPushImage

    dependsOn: TestApplication
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    pool:
      name: hmcts-pet

    steps:
    - template: ./pipeline-steps/docker-build.yaml
      parameters:
        azureContainerRegistry: $(azure.container.registry)
        azureSubscriptionEndpoint: $(azure.subscription.endpoint)
        applicationName: $(application.name)


  - job: ManualBuildAndPushImage
  
    dependsOn: TestApplication
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.Reason'], 'Manual'))
    pool:
      name: hmcts-pet

    steps:
    - template: ./pipeline-steps/manual-docker-build.yaml
      parameters:
        azureContainerRegistry: $(azure.container.registry)
        azureSubscriptionEndpoint: $(azure.subscription.endpoint)
        manualBranchPrefix: $(manual.branch.prefix)
        applicationName: $(application.name)
