base:
  applicationPort: 3000
  readinessPath: /status
  livenessPath: /status
  startupPath: /status
  image: 'sdshmctspublic.azurecr.io/hwf-publicapp/application:latest'
  ingressHost: hwf-publicapp.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: help-with-fees
  environment:
    RAILS_ENV: 'production'
  keyVaults:
    help-with-fees:
      secrets:
        - name: hwf-fqdn
          alias: DATABASE_HOST
        - name: hwf-username
          alias: DATABASE_USERNAME
        - name: hwf-password
          alias: DATABASE_PASSWORD





