env: <%= ENV['ENV'] %>
submission:
  url: <%= ENV['SUBMISSION_URL'] %>
  token: <%= ENV['SUBMISSION_TOKEN'] %>
analytics:
  id: <%= ENV['GTM_ID'] || 'GTM-MBQ9L9X' %>
health_status:
  deployment:
    version_number: <%= ENV['APPVERSION'] || 'unknown' %>
    build_date: <%= ENV['APP_BUILD_DATE'] || 'unknown' %>
    commit_id:  <%= ENV['APP_GIT_COMMIT'] || 'unknown' %>
    build_tag:  <%= ENV['APP_BUILD_TAG'] || 'unknown' %>
session:
  expires_in_minutes: 60
et:
  england_wales_email: ETHelpwithfees@hmcts.gsi.gov.uk
  scotland_email: GLASGOWET@hmcts.gsi.gov.uk
homepage:
  external_url: <%= ENV['HOMEPAGE_EXTERNAL_URL'] || nil %>
done_page:
  external_url: <%= ENV['DONE_PAGE_EXTERNAL_URL'] || nil %>
income:
  min_threshold_base: 1170
  max_threshold_base: 5170
  per_child_increment: 265
  married_supplement: 175
probate_fees:
  release_date: <%= ENV['PROBATE_FEES_RELEASE_DATE'] || '2025-04-01' %>
sentry:
  dsn: <%= ENV['SENTRY_DSN'] %>
maintenance:
  show: <%= ENV['SHOW_MAINTENANCE_BANNER'] || false %>
mail:
  help_me: <%= ENV['HELP_ME_EMAIL'] %>
navigation:
  old_default:
    - :form_name
    - :fee
    - :national_insurance_presence
    - :national_insurance
    - :home_office
    - :marital_status
    - :savings_and_investment
    - :savings_and_investment_extra
    - :benefit
    - :dependent
    - :income_kind
    - :income_range
    - :income_amount
    - :probate
    - :claim
    - :dob
    - :personal_detail
    - :applicant_address
    - :contact
    - :apply_type
  pre_ucd_changes:
    - :fee
    - :form_name
    - :national_insurance_presence
    - :national_insurance
    - :home_office
    - :marital_status
    - :savings_and_investment
    - :savings_and_investment_extra
    - :benefit
    - :dependent
    - :income_kind
    - :income_range
    - :income_amount
    - :probate
    - :claim
    - :dob
    - :personal_detail
    - :applicant_address
    - :contact
    - :apply_type
  post_ucd_changes:
    - :fee
    - :form_name
    - :applying_on_behalf
    - :legal_representative
    - :legal_representative_detail
    - :over_16
    - :national_insurance_presence
    - :national_insurance
    - :home_office
    - :marital_status
    - :savings_and_investment
    - :savings_and_investment_extra
    - :benefit
    - :dependent
    - :income_kind
    - :income_range
    - :income_amount
    - :probate
    - :claim
    - :dob
    - :personal_detail
    - :applicant_address
    - :contact
    - :apply_type

feature_switching:
  - feature_key: "ucd_refactor"
    enabled: true
  - feature_key: "band test"
    enabled: false
legislation_work:
  active_date: <%= ENV['NEW_LEGISLATION_ACTIVE_DATE'] || '27-10-2023' %>