env: <%= ENV['ENV'] %>
submission:
  url: <%= ENV['SUBMISSION_URL'] %>
  token: <%= ENV['SUBMISSION_TOKEN'] %>
analytics:
  id: <%= ENV['GTM_ID'] || 'GTM-MBQ9L9X' %>
health_status:
  deployment:
    version_number: <%= ENV['APPVERSION'] || 'unknown' %>
    build_date: <%= ENV['APP_BUILD_DATE'] || 'unknown' %>
    commit_id:  <%= ENV['APP_GIT_COMMIT'] || 'unknown' %>
    build_tag:  <%= ENV['APP_BUILD_TAG'] || 'unknown' %>
session:
  expires_in_minutes: 60
session_store:
  valid_domains:
    - helpwithcourtfees.service.gov.uk
    - hwf-publicapp.aat.platform.hmcts.net
    - hwf-publicapp.demo.platform.hmcts.net
et:
  england_wales_email: ETHelpwithfees@hmcts.gsi.gov.uk
  scotland_email: GLASGOWET@hmcts.gsi.gov.uk
homepage:
  external_url: <%= ENV['HOMEPAGE_EXTERNAL_URL'] || nil %>
done_page:
  external_url: <%= ENV['DONE_PAGE_EXTERNAL_URL'] || nil %>
income:
  min_threshold_base: 1170
  max_threshold_base: 5170
  per_child_increment: 265
  married_supplement: 175
probate_fees:
  release_date: <%= ENV['PROBATE_FEES_RELEASE_DATE'] || '2026-04-01' %>
new_branding:
  new_branding_date: <%= ENV['NEW_BRANDING_DATE'] || '2024-06-25' %>
sentry:
  dsn: <%= ENV['SENTRY_DSN'] %>
maintenance:
  show: <%= ENV['SHOW_MAINTENANCE_BANNER'] || false %>
mail:
  help_me: <%= ENV['HELP_ME_EMAIL'] %>
navigation:
  - :fee
  - :form_name
  - :applying_on_behalf
  - :legal_representative
  - :legal_representative_detail
  - :over_16
  - :national_insurance
  - :home_office
  - :marital_status
  - :partner_national_insurance
  - :savings_and_investment
  - :savings_and_investment_extra
  - :benefit
  - :dependent
  - :income_kind
  - :income_period
  - :probate
  - :claim
  - :dob
  - :personal_detail
  - :applicant_address
  - :contact
  - :apply_type

feature_switching:
  - feature_key: "band test"
    enabled: false