parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '$(rubyVersion)'

- script: |
    gem install bundler -v $(bundlerVersion)
  displayName: 'install bundler'

- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    bundle exec rubocop --fail-fast
  displayName: 'rubocop'

- script: |
    bundle exec brakeman
  displayName: 'brakeman'

- script: |
    bundle exec rspec --fail-fast --format documentation --format RspecJunitFormatter --out test-rspec.xml
  displayName: 'rspec'

- script: |
    bundle exec cucumber features/*.feature --fail-fast
  displayName: 'cucumber'

- script: |
<<<<<<< HEAD
     bundle exec rails s -p 3001 & sleep 5; npm run pa11y-ci
=======
    bundle exec rails s -p 3001 & sleep 5; npm run pa11y-ci
>>>>>>> d2f1e70 (add port when running rails)
  displayName: 'pa11y'