parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- script: |
    mv .dockerignore .dockerignore.backup
    cp Dockerfile.test.dockerignore .dockerignore
    docker-compose -f docker-compose-test.yml run --rm test
    rm .dockerignore
    mv .dockerignore.backup .dockerignore
  displayName: 'Docker compose tests'


# parameters:
#   rubyVersion: ''
#   bundlerVersion: ''


# steps:
# - task: UseRubyVersion@0
#   inputs:
#     versionSpec: '$(rubyVersion)'

# - script: |
#     gem install bundler -v $(bundlerVersion)
#   displayName: 'install bundler'

# - script: |
#     bundle install --retry=3 --jobs=4
#   displayName: 'bundle install'

# - script: |
#     npm install --production
#   displayName: 'npm install'

# - script: |
#     bundle exec rubocop --fail-fast
#   displayName: 'rubocop'

# - script: |
#     bundle exec brakeman
#   displayName: 'brakeman'

# - script: |
#     bundle exec rake parallel:spec RAILS_ENV=test
#   displayName: 'rspec'

# - script: |
#     CAPYBARA_SERVER_PORT=random bundle exec rake parallel:features
#   displayName: 'cucumber'
