parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- script: |
    mv .dockerignore .dockerignore.backup
    cp Dockerfile.test.dockerignore .dockerignore
    docker-compose -f docker-compose-test.yml run --rm test
    rm .dockerignore
    mv .dockerignore.backup .dockerignore
  displayName: 'Docker compose tests'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '$(rubyVersion)'

- script: |
    gem install bundler -v $(bundlerVersion)
    bundle install --retry=3 --jobs=4
    npm install --production
  displayName: 'cucumber setup'

- script: |
    CAPYBARA_SERVER_PORT=random bundle exec rake parallel:features
  displayName: 'cucumber test'
