parameters:
  rubyVersion: ''
  bundlerVersion: ''


steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '$(rubyVersion)'

- script: |
    gem install bundler -v $(bundlerVersion)
  displayName: 'install bundler'

- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    bundle exec rubocop
    bundle exec rspec --format documentation --format RspecJunitFormatter --out test-rspec.xml
    bundle exec cucumber features/*.feature
  displayName: 'tests'

