base:
  applicationPort: 3000
  readinessPath: /ping.json
  livenessPath: /ping.json
  startupPath: /ping.json
  image: 'hmctspublic.azurecr.io/help-with-fees/publicapp:latest'
  ingressHost: hwf-publicapp.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: help-with-fees
  environment:
    RAILS_ENV: 'production'
    SECRETS_PATH: "/mnt/secrets/help-with-fees"
    SERVICE_FQDN: ${SERVICE_FQDN}
  keyVaults:
    help-with-fees:
      secrets:
        - name: prod-hwf-public-secret-token
          alias: prod-hwf-public-secret-token
        - name: dev-hwf-public-secret-token
          alias: SECRET_KEY_BASE
