base:
  applicationPort: 3000
  readinessPath: /status
  livenessPath: /status
  startupPath: /status
  image: 'hmctspublic.azurecr.io/help-with-fees/publicapp:latest'
  ingressHost: hwf-publicapp.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: help-with-fees
  environment:
    RAILS_ENV: 'production'
    SECRET_KEY_BASE:
      secretRef: "dev-hwf-public-secret-token"
      key: "dev-hwf-public-secret-token"
      disabled: false
  keyVaults:
    help-with-fees:
      secrets:
        - name: hwf-fqdn
          alias: DATABASE_HOST
        - name: hwf-username
          alias: DATABASE_USERNAME
        - name: hwf-password
          alias: DATABASE_PASSWORD
        - name: prod-hwf-public-secret-token
          alias: prod-hwf-public-secret-token




